### ISSUE TITLE
No accelerometer reading at all

### ISSUE THREAD

**Issue by callgino** [maxosprojects/open-dobot#39] opened 2017-01-08 14:18 UTC
Accelerometers give no reading at all.
My Dobot was working OK before installing open dobot, this is not a hardware issue.
Tried instructions in calibrate-accelerometers.py, nothing changed.

1) Using open dobot 1.3.0
2) FPGA, all original dobot hardware
3) Arm Dobot version 1.2
4) Ubuntu 16.04

**Comment by maxosprojects** [comment] 2017-01-08 21:50
Duplicate of #26

**Closed as completed by maxosprojects** 2017-01-08 21:50 UTC
Labels: duplicate
